### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by priyambial123** [PengNi/ccsmeth#17]
Hello

I used the below code to call methyl modifications:

```
CUDA_VISIBLE_DEVICES=0 ccsmeth call_mods \
  --input /scicore/home/cichon/GROUP/PacBio_workflow/methylation/002-016/Xt4Y5lka_mapped.bam \
  --ref /scicore/home/cichon/GROUP/PacBio_workflow/workflow/workflow/reference/human_GRCh38_no_alt_analysis_set.fasta \
  --model_file /scicore/home/cichon/GROUP/PacBio_workflow/methylation/002-016/ccsmeth/build/lib/ccsmeth/ \
  --output /scicore/home/cichon/GROUP/PacBio_workflow/methylation/002-016/output_ccsmeth/ \
  --threads 10 --threads_call 2 --model_type attbigru2s
```

I got the below error:

```
Traceback (most recent call last):
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/bin/ccsmeth", line 33, in <module>
    sys.exit(load_entry_point('ccsmeth==0.2.3', 'console_scripts', 'ccsmeth')())
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/ccsmeth-0.2.3-py3.7.egg/ccsmeth/ccsmeth.py", line 769, in main
    args.func(args)
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/ccsmeth-0.2.3-py3.7.egg/ccsmeth/ccsmeth.py", line 27, in main_call_mods
    from .call_modifications import call_mods
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/ccsmeth-0.2.3-py3.7.egg/ccsmeth/call_modifications.py", line 14, in <module>
    from sklearn import metrics
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/sklearn/base.py", line 11, in <module>
    from scipy import sparse
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 231, in <module>
    from .csr import *
  File "/scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /scicore/home/cichon/thirun0000/miniconda3/envs/ccsmethenv/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)

I checked using the grep command

sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so | grep CXXABI
 
Found no  CXXABI module. Should I do the installation again

Thanks
Priya

**Comment by PengNi** [comment]
Hi Priya, thanks very much for your interest of ccsmeth. However ccsmeth is still under development, and we haven't release a stable version for research use right now. I will release a stable version ASAP.

Best,
Peng

**Comment by PengNi** [comment]
It is recommanded to install ccsmeth using conda as the way provided in README.
