### ISSUE TITLE
TypeError: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by SarahChen0401** [PengNi/ccsmeth#2]
Hi, Peng. 
When I run this command:
```
ccsmeth extract --input chr22.ccs.subreads.bam --ref hg38.fa --threads 5 --norm zscore --comb_strands --depth 1 --output chr22.ccs.subreads.features.zscore.fb.depth1.tsv 
```
I got these messages:
```
## parameters:
input:
	chr22.ccs.subreads.bam
ref:
	hg38.fa
holeids_e:
	None
holeids_ne:
	None
output:
	chr22.ccs.subreads.bam.features.zscore.fb.depth1.tsv
seq_len:
	21
motifs:
	CG
mod_loc:
	0
methy_label:
	1
mapq:
	20
identity:
	0.8
two_strands:
	False
comb_strands:
	True
depth:
	1
norm:
	zscore
no_decode:
	False
num_subreads:
	0
path_to_samtools:
	None
holes_batch:
	50
seed:
	1234
threads:
	10
# ===============================================
[extract_features]start..
read_input process-520151 starts
cmd to view input: samtools view -@ 3 -h chr22.ccs.subreads.bam
extrac_features process-520153 starts
extrac_features process-520156 starts
extrac_features process-520161 starts
extrac_features process-520167 starts
extrac_features process-520168 starts
extrac_features process-520169 starts
extrac_features process-520170 starts
extrac_features process-520171 starts
write_process-520172 started
Process Process-9:
Traceback (most recent call last):
  File "/home/chenshuhua/.local/opt/miniconda_v4.9.2_d20210310/envs/ccsmethenv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/chenshuhua/.local/opt/miniconda_v4.9.2_d20210310/envs/ccsmethenv/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chenshuhua/.local/opt/miniconda_v4.9.2_d20210310/envs/ccsmethenv/lib/python3.6/site-packages/ccsmeth-0.1.0-py3.6.egg/ccsmeth/extract_features.py", line 543, in _worker_extract
    feature_list += handle_one_hole2(hole_aligninfo, contigs, motifs, args)
  File "/home/chenshuhua/.local/opt/miniconda_v4.9.2_d20210310/envs/ccsmethenv/lib/python3.6/site-packages/ccsmeth-0.1.0-py3.6.egg/ccsmeth/extract_features.py", line 451, in handle_one_hole2
    feature_list += _comb_fb_features(fwd_features, bwd_features)
  File "/home/chenshuhua/.local/opt/miniconda_v4.9.2_d20210310/envs/ccsmethenv/lib/python3.6/site-packages/ccsmeth-0.1.0-py3.6.egg/ccsmeth/extract_features.py", line 362, in _comb_fb_features
    ffea[4] = max(ffea[4], bfea[4])
TypeError: 'tuple' object does not support item assignment

``` 
Looking forward to your reply.

Best wishes,
Shuhua

**Comment by PengNi** [comment]
Hi shuhua,

Thanks for your interest of our tool! This TypeError was a bug. I have fixed it and updated the code. Please try the latest version of ccsmeth.

Best,
Peng

**Comment by SarahChen0401** [comment]
> Hi shuhua,
> 
> Thanks for your interest of our tool! This TypeError was a bug. I have fixed it and updated the code. Please try the latest version of ccsmeth.
> 
> Best, Peng

**Comment by SarahChen0401** [comment]
> Hi shuhua,
> 
> Thanks for your interest of our tool! This TypeError was a bug. I have fixed it and updated the code. Please try the latest version of ccsmeth.
> 
> Best, Peng

thanks for your nice reply~
