### ISSUE TITLE
Call modification 

### ISSUE THREAD

**Issue by RahelehSalehi** [PengNi/ccsmeth#31]
Hi Peng,
Thanks again for ccsmeth. You suggested using "Quick start", I have a question related to the call modification step and train step. What is the difference between the two steps? If I skip the modification call and after the first and second steps, extract the features from hifi reads, that would be correct? Why should I do the modification step?

Thanks a lot for your time and help.

**Comment by olaraym** [comment]
I guess the call modification step is important because that gives you the modification probabilities of each potentially methylated cytosine base and also it gives you the sequence context of methylation and other information.

**Comment by PengNi** [comment]
@RahelehSalehi , train step is for traing a new model for modification calling, while call modificatino step calls per-read modifications from `ccs.ban` with a pre-trained model as @olaraym said.

**Comment by RahelehSalehi** [comment]
Dear PengNi,
I ran ccsmeth call_mods on my dataset. the problem is that after 21% of running, the running process is frozen and it doesn't work. I got the following errors:   File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
Process Process-4:
Traceback (most recent call last):
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/ccsmeth/call_modifications.py", line 301, in _call_mods_q
    para_dict = torch.load(model_path, map_location=torch.device('cpu'))
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
split_holebatches process-1579883 generates 9347 hole/read batches(50)
Could you please help me, with how I can solve my problem?

Thanks alot.

**Comment by PengNi** [comment]
> Dear PengNi, I ran ccsmeth call_mods on my dataset. the problem is that after 21% of running, the running process is frozen and it doesn't work. I got the following errors: File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, '{'. Process Process-4: Traceback (most recent call last): File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/ccsmeth/call_modifications.py", line 301, in _call_mods_q para_dict = torch.load(model_path, map_location=torch.device('cpu')) File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 713, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, '{'. split_holebatches process-1579883 generates 9347 hole/read batches(50) Could you please help me, with how I can solve my problem?
> 
> Thanks alot.

I guess this is because the model ckpt file doesn't match the version of ccsmeth. Please update ccsmeth to the latest version, and use the latest model in the `models' directory, and then try again.  If you still have problems, please contact me again. Thank you.

Best,
Peng

**Comment by RahelehSalehi** [comment]
Thanks a lot for the quick reply.  I updated ccsmeth in the new version, it is frozen again at the beginning, I got the following error: 
Traceback (most recent call last):
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/ccsmeth-0.4.1-py3.8.egg/ccsmeth/call_modifications.py", line 327, in _call_mods_q
    para_dict = torch.load(model_path, map_location=torch.device('cpu'))
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
Traceback (most recent call last):
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/ccsmeth-0.4.1-py3.8.egg/ccsmeth/call_modifications.py", line 327, in _call_mods_q
    para_dict = torch.load(model_path, map_location=torch.device('cpu'))
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
2023-07-11 09:06:21 - INFO - split_holebatches process-2083568 generates 9347 hole/read batches(50)
batch_reader:   1%|▋                                                                                             | 65/9347 [00:19<04:10, 37.01it/s]
Thanks a lot to help me out.

**Comment by PengNi** [comment]
@RahelehSalehi , could you tell me the exact command and the model file you are using?

**Comment by RahelehSalehi** [comment]
Of course, I use this:
ccsmeth call_mods --input /playground/AK_Giehr/user/rahelehsalehi/Ssm/SEQ00XX/2-Align/call-align-16/data/hifi-SEQ00XX-barcode-16.pbmm2.bam --ref /playground/AK_Giehr/genomes/ncbi/Escherichia_phage_Lambda/GCF_000840245.1_ViralProj14204_genomic.fasta --model_file /playground/AK_Giehr/user/rahelehsalehi/Ssm/SEQ00XX/3-Call-Mod/On_Cluster/traind-model/model_ccsmeth_5mCpG_aggregate_attbigru_b11.v2p.ckpt --output /playground/AK_Giehr/user/rahelehsalehi/Ssm/SEQ00XX/3-Call-Mod/On_Cluster/Call-mod-16/data/SEQ00XX-barcode-16.hifi.pbmm2.call_mods --threads 10 --threads_call 2 --mode align --model_type attbilstm2s

**Comment by RahelehSalehi** [comment]
It seems it works, thanks alot

**Comment by RahelehSalehi** [comment]
still, the error is there: 
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
2023-07-11 09:36:34 - INFO - extract_features process-2090330 starts
2023-07-11 09:36:34 - INFO - extract_features process-2089363 starts
2023-07-11 09:36:34 - INFO - extract_features process-2089370 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090315 starts
2023-07-11 09:36:35 - INFO - split_holebatches process-2089361 generates 9347 hole/read batches(50)
batch_reader:   0%|                                                                                                                                        | 0/9347 [00:00<?, ?it/s]2023-07-11 09:36:35 - INFO - extract_features process-2091049 starts
2023-07-11 09:36:35 - INFO - extract_features process-2089369 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090653 starts
2023-07-11 09:36:35 - INFO - extract_features process-2089371 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090941 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091452 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091309 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091052 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091126 starts
2023-07-11 09:36:35 - INFO - extract_features process-2089365 starts
2023-07-11 09:36:35 - INFO - extract_features process-2089367 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091382 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091454 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091055 starts
batch_reader:   0%|▏                                                                                                                             | 18/9347 [00:00<00:53, 175.16it/s]2023-07-11 09:36:35 - INFO - extract_features process-2089373 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091387 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091652 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091409 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091648 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091124 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091192 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091536 starts
2023-07-11 09:36:35 - INFO - extract_features process-2089372 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090518 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091583 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090848 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091045 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091650 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091125 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091717 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091054 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090783 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091181 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090670 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091582 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091651 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091050 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091107 starts
batch_reader:   0%|▌                                                                                                                             | 38/9347 [00:00<00:49, 186.79it/s]2023-07-11 09:36:35 - INFO - extract_features process-2091257 starts
2023-07-11 09:36:35 - INFO - extract_features process-2090980 starts
2023-07-11 09:36:35 - INFO - extract_features process-2089632 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091056 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091047 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091258 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091649 starts
2023-07-11 09:36:35 - INFO - extract_features process-2091059 starts
batch_reader:   5%|██████▎                                                                                                                      | 469/9347 [00:19<00:33, 263.97it/s]

**Comment by RahelehSalehi** [comment]
Thanks, I used all your recommendations, and still, the error is there. It seems the error is related to pickle library. Maybe I should use another version of python?
  File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.

**Comment by PengNi** [comment]
@RahelehSalehi , thanks for your patience. I can't reproduce this error myself. Maybe you can try the [One-step installation](https://github.com/PengNi/ccsmeth#option-1-one-step-installation) in README to re-install a virtual environment.

If it still doesn't work, please show me the version of all packages in your environment by using `conda list`.

> Thanks, I used all your recommendations, and still, the error is there. It seems the error is related to pickle library. Maybe I should use another version of python? File "/home/rsalehi/miniconda3/envs/ccsmethenv/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, '{'.

**Comment by RahelehSalehi** [comment]
I reinstalled again ccsmeth package and still the error is coming up. Please find the version of all packages in my environment here:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
bedtools                  2.26.0                        0    bioconda
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.0               h5eee18b_0  
ca-certificates           2023.05.30           h06a4308_0  
ccsmeth                   0.4.1                    pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_1  
curl                      8.1.1                h5eee18b_1  
cython                    0.29.36                  pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305  
joblib                    1.3.1                    pypi_0    pypi
krb5                      1.20.1               h568e23c_1  
ld_impl_linux-64          2.38                 h1181459_1  
libcurl                   8.1.1                h91b91d3_1  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_0  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libnghttp2                1.52.0               ha637b67_1  
libssh2                   1.10.0               h37d81fd_2  
libstdcxx-ng              11.2.0               h1234567_1  
libuv                     1.44.2               h5eee18b_0  
mkl                       2023.1.0         h6d00ec8_46342  
ncurses                   6.4                  h6a678d5_0  
numpy                     1.24.4                   pypi_0    pypi
openssl                   1.1.1u               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pbccs                     6.4.0                h9ee0642_0    bioconda
pbmm2                     1.12.0               h9ee0642_0    bioconda
pip                       23.1.2           py38h06a4308_0  
pybedtools                0.9.0                    pypi_0    pypi
pysam                     0.21.0                   pypi_0    pypi
pytabix                   0.1                      pypi_0    pypi
python                    3.8.17               h7a1cb2a_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.11.0          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
samtools                  1.5                           1    bioconda
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.8.0           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
statsmodels               0.14.0                   pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     1.12.1                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
typing_extensions         4.6.3            py38h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0

**Comment by PengNi** [comment]
@RahelehSalehi , from the versions I still can't find any problem. May you list the directory that you use to save the models (the `/playground/AK_Giehr/user/rahelehsalehi/Ssm/SEQ00XX/3-Call-Mod/On_Cluster/traind-model/` dir) by `ls -la`? Maybe there are problems in the model files.

**Comment by RahelehSalehi** [comment]
Of course! Here you are:
<img width="996" alt="Screenshot 2023-07-11 at 14 52 19" src="https://github.com/PengNi/ccsmeth/assets/108475936/6fc1ea56-1940-4e6c-a6f4-8651eb11b568">

**Comment by RahelehSalehi** [comment]
There is no error now, but it is still frozen after 5% of the process. Do you have any suggestions?
	1234
# ===============================================
2023-07-11 15:47:29 - INFO - [main]call_mods starts
2023-07-11 15:47:29 - INFO - cuda availability: False
2023-07-11 15:47:30 - INFO - split_holebatches process-2353074 starts
2023-07-11 15:47:32 - INFO - extract_features process-2353340 starts
2023-07-11 15:47:32 - INFO - extract_features process-2353185 starts
2023-07-11 15:47:32 - INFO - extract_features process-2353276 starts
2023-07-11 15:47:32 - INFO - extract_features process-2353406 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353405 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353472 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354499 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354645 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353076 starts
2023-07-11 15:47:33 - INFO - call_mods process-2353077 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353341 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353418 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353718 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354507 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354512 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353212 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353120 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353082 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353078 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355208 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355577 starts
2023-07-11 15:47:33 - INFO - call_mods process-2353079 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354040 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353081 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354504 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354506 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353080 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355546 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355547 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354509 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354360 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354364 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354430 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355093 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354511 starts
2023-07-11 15:47:33 - INFO - extract_features process-2353083 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355469 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354496 starts
2023-07-11 15:47:33 - INFO - split_holebatches process-2353074 generates 9347 hole/read batches(50)
batch_reader:   0%|                                                                                                                                               | 0/9347 [00:00<?, ?it/s]2023-07-11 15:47:33 - INFO - extract_features process-2355351 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355092 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354298 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354169 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355471 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354233 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354773 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355099 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354495 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354362 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354516 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354498 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354502 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354901 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355095 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354514 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355576 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354510 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354287 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354428 starts
batch_reader:   0%|▎                                                                                                                                    | 26/9347 [00:00<00:36, 252.16it/s]2023-07-11 15:47:33 - INFO - extract_features process-2354518 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354513 starts
2023-07-11 15:47:33 - INFO - extract_features process-2355088 starts
2023-07-11 15:47:33 - INFO - extract_features process-2354361 starts
batch_reader:   5%|██████▍                                                                                                                             | 459/9347 [00:02<00:40, 218.67it/s]batch_reader:   5%|██████▋                                                                                                                             | 471/9347 [00:19<00:40, 218.67i

**Comment by PengNi** [comment]
> There is no error now, but it is still frozen after 5% of the process. Do you have any suggestions? 1234
> 
> # ===============================================
> 2023-07-11 15:47:29 - INFO - [main]call_mods starts 2023-07-11 15:47:29 - INFO - cuda availability: False 2023-07-11 15:47:30 - INFO - split_holebatches process-2353074 starts 2023-07-11 15:47:32 - INFO - extract_features process-2353340 starts 2023-07-11 15:47:32 - INFO - extract_features process-2353185 starts 2023-07-11 15:47:32 - INFO - extract_features process-2353276 starts 2023-07-11 15:47:32 - INFO - extract_features process-2353406 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353405 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353472 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354499 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354645 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353076 starts 2023-07-11 15:47:33 - INFO - call_mods process-2353077 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353341 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353418 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353718 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354507 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354512 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353212 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353120 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353082 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353078 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355208 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355577 starts 2023-07-11 15:47:33 - INFO - call_mods process-2353079 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354040 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353081 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354504 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354506 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353080 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355546 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355547 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354509 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354360 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354364 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354430 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355093 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354511 starts 2023-07-11 15:47:33 - INFO - extract_features process-2353083 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355469 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354496 starts 2023-07-11 15:47:33 - INFO - split_holebatches process-2353074 generates 9347 hole/read batches(50) batch_reader: 0%| | 0/9347 [00:00<?, ?it/s]2023-07-11 15:47:33 - INFO - extract_features process-2355351 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355092 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354298 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354169 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355471 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354233 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354773 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355099 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354495 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354362 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354516 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354498 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354502 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354901 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355095 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354514 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355576 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354510 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354287 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354428 starts batch_reader: 0%|▎ | 26/9347 [00:00<00:36, 252.16it/s]2023-07-11 15:47:33 - INFO - extract_features process-2354518 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354513 starts 2023-07-11 15:47:33 - INFO - extract_features process-2355088 starts 2023-07-11 15:47:33 - INFO - extract_features process-2354361 starts batch_reader: 5%|██████▍ | 459/9347 [00:02<00:40, 218.67it/s]batch_reader: 5%|██████▋ | 471/9347 [00:19<00:40, 218.67i

@RahelehSalehi, maybe this is because the process is too slow. We recommend to use a GPU machine for call_mods if available.

Best,
Peng

**Comment by RahelehSalehi** [comment]
Thank you so much for your response. I tried on GPU as well, before that I reinstalled the ccsmeth package, then I ran the command, and the following error is coming up. Do you have any suggestions?
![Screenshot from 2023-07-12 11-33-13](https://github.com/PengNi/ccsmeth/assets/108475936/ce070ccf-bb58-4b96-aaa9-78b69b0cb565)

**Comment by PengNi** [comment]
> Thank you so much for your response. I tried on GPU as well, before that I reinstalled the ccsmeth package, then I ran the command, and the following error is coming up. Do you have any suggestions? ![Screenshot from 2023-07-12 11-33-13](https://user-images.githubusercontent.com/108475936/252933414-ce070ccf-bb58-4b96-aaa9-78b69b0cb565.png)

Hi @RahelehSalehi , what's the command and the model file you used?

**Comment by RahelehSalehi** [comment]
I used this command: 

ccsmeth call_mods --input /data/raheleh_salehi/Strand-Specific-Methylation/SEQ00XX/3-Call-Mod/Dataset/call-align-16/data/hifi-SEQ00XX-barcode-16.pbmm2.bam --ref /data/raheleh_salehi/Strand-Specific-Methylation/SEQ00XX/3-Call-Mod/Dataset/genome/GCF_000840245.1_ViralProj14204_genomic.fasta --model_file /data/raheleh_salehi/Strand-Specific-Methylation/SEQ00XX/3-Call-Mod/traind-model/model_ccsmeth_5mCpG_call_mods_attbigru2s_b21.v2.ckpt --output /data/raheleh_salehi/Strand-Specific-Methylation/SEQ00XX/3-Call-Mod/Call-mod-16/data/SEQ00XX-barcode-16.hifi.pbmm2.call_mods --threads 10 --threads_call 2 --mode align --model_type attbilstm2s

and the model is model_ccsmeth_5mCpG_call_mods_attbigru2s_b21.v2.ckpt

**Comment by PengNi** [comment]
@RahelehSalehi ， please use `--model_type attbigru2s` and try again.

**Comment by RahelehSalehi** [comment]
Thanks alot, I change the model_type, there is no error, but still it is frozen :(
![Screenshot from 2023-07-12 13-44-13](https://github.com/PengNi/ccsmeth/assets/108475936/94b577c1-786e-4fa5-be16-8e68538d21ac)

**Comment by PengNi** [comment]
@RahelehSalehi , maybe it is because the GPU card in your machine is too new for the pytorch and CUDA version in the virtual environment. ref: [https://discuss.pytorch.org/t/nvidia-geforce-rtx-3090-with-cuda-capability-sm-86-is-not-compatible-with-the-current-pytorch-installation/141940](https://discuss.pytorch.org/t/nvidia-geforce-rtx-3090-with-cuda-capability-sm-86-is-not-compatible-with-the-current-pytorch-installation/141940).

What is the CUDA driver version in your machine? can you show me what `nvidia-smi` shows? If the CUDA driver version in your machine is greater than 11.3, then you can reinstall pytorch in the ccsmethenv virtual environment by:
```
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
```

**Comment by jdcc2098** [comment]
Hey @RahelehSalehi I don't know if you have solved this problem, but I think this may help:

I have the same error noting "_pickle.UnpicklingError: invalid load key"
I checked the model file. Turns out that, the link doesn't provide direct download but it links to a github's file page.
So you may have downloaded a html document, not a model.

The correct model file should be ~12Mb rather than ~200kb.

@PengNi Maybe replacing with a direct `raw.githubusercontent.com` link for model downloading can prevent this problem.
