### ISSUE TITLE
卡在11%不动了

### ISSUE THREAD

**Issue by rl4940** [PengNi/ccsmeth#34]
你好！
我做了call_mod
然后error_output给了下面这个：
```
split_holebatches process-19085 starts
extract_features process-19087 starts
[W::hts_idx_load3] The index file is older than the data file: /gpfs/data/pirontilab/Students/data/RobPacBio/121A/mapped.bam.bai
extract_features process-19095 starts
/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA A100 80GB PCIe with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA A100 80GB PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
extract_features process-19110 starts
/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA A100 80GB PCIe with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA A100 80GB PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
extract_features process-19144 starts
extract_features process-19152 starts
split_holebatches process-19085 generates 9340 hole/read batches(50)

batch_reader:   0%|          | 0/9340 [00:00<?, ?it/s][W::hts_idx_load3] The index file is older than the data file: /gpfs/data/pirontilab/Students/data/RobPacBio/121A/mapped.bam.bai
Process Process-8:
Process Process-5:

batch_reader:   0%|          | 10/9340 [00:00<11:41, 13.30it/s]Traceback (most recent call last):
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 531, in worker_extract_features_from_holebatches
    features_batch = _batch_feature_list2s(features_batch)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 480, in _batch_feature_list2s
    fipdms.append(np.array(kmer_ipdm, dtype=np.float))
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 531, in worker_extract_features_from_holebatches
    features_batch = _batch_feature_list2s(features_batch)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 480, in _batch_feature_list2s
    fipdms.append(np.array(kmer_ipdm, dtype=np.float))
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

batch_reader:   0%|          | 16/9340 [00:00<07:29, 20.76it/s]Process Process-3:
Process Process-9:
Process Process-7:
Traceback (most recent call last):
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 531, in worker_extract_features_from_holebatches
    features_batch = _batch_feature_list2s(features_batch)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 480, in _batch_feature_list2s
    fipdms.append(np.array(kmer_ipdm, dtype=np.float))
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

batch_reader:   0%|          | 21/9340 [00:01<11:19, 13.71it/s]Traceback (most recent call last):
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 531, in worker_extract_features_from_holebatches
    features_batch = _batch_feature_list2s(features_batch)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 480, in _batch_feature_list2s
    fipdms.append(np.array(kmer_ipdm, dtype=np.float))
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 531, in worker_extract_features_from_holebatches
    features_batch = _batch_feature_list2s(features_batch)
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/ccsmeth/extract_features.py", line 480, in _batch_feature_list2s
    fipdms.append(np.array(kmer_ipdm, dtype=np.float))
  File "/gpfs/data/pirontilab/Students/software/conda/envs/ccsmeth/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

batch_reader:   0%|          | 27/9340 [00:01<08:04, 19.20it/s]
batch_reader:   0%|          | 38/9340 [00:01<04:46, 32.51it/s]
batch_reader:   1%|          | 58/9340 [00:01<02:31, 61.11it/s]
batch_reader:   1%|          | 77/9340 [00:01<01:47, 86.55it/s]
batch_reader:   1%|          | 94/9340 [00:01<01:32, 100.23it/s]
batch_reader:   1%|          | 113/9340 [00:02<01:16, 120.08it/s]
batch_reader:   1%|▏         | 132/9340 [00:02<01:07, 136.62it/s]
batch_reader:   2%|▏         | 151/9340 [00:02<01:01, 149.84it/s]
batch_reader:   2%|▏         | 168/9340 [00:02<01:02, 146.20it/s]
batch_reader:   2%|▏         | 187/9340 [00:02<00:58, 157.36it/s]
batch_reader:   2%|▏         | 207/9340 [00:02<00:54, 167.52it/s]
batch_reader:   2%|▏         | 227/9340 [00:02<00:51, 175.88it/s]
batch_reader:   3%|▎         | 247/9340 [00:02<00:50, 180.27it/s]
batch_reader:   3%|▎         | 266/9340 [00:02<00:55, 162.07it/s]
batch_reader:   3%|▎         | 286/9340 [00:03<00:52, 171.92it/s]
batch_reader:   3%|▎         | 306/9340 [00:03<00:50, 177.51it/s]
batch_reader:   3%|▎         | 326/9340 [00:03<00:49, 182.13it/s]
batch_reader:   4%|▎         | 346/9340 [00:03<00:48, 184.52it/s]
batch_reader:   4%|▍         | 365/9340 [00:03<01:37, 91.77it/s] 
batch_reader:   4%|▍         | 385/9340 [00:03<01:21, 109.33it/s]
batch_reader:   4%|▍         | 401/9340 [00:04<01:31, 97.67it/s] 
batch_reader:   4%|▍         | 420/9340 [00:04<01:17, 114.61it/s]
batch_reader:   5%|▍         | 440/9340 [00:04<01:07, 132.07it/s]
batch_reader:   5%|▍         | 460/9340 [00:04<01:00, 146.57it/s]
batch_reader:   5%|▌         | 480/9340 [00:04<00:55, 158.23it/s]
batch_reader:   5%|▌         | 498/9340 [00:04<01:01, 142.78it/s]
batch_reader:   6%|▌         | 518/9340 [00:04<00:56, 154.90it/s]
batch_reader:   6%|▌         | 538/9340 [00:04<00:53, 165.79it/s]
batch_reader:   6%|▌         | 558/9340 [00:05<00:50, 173.70it/s]
batch_reader:   6%|▌         | 578/9340 [00:05<00:49, 178.79it/s]
batch_reader:   6%|▋         | 598/9340 [00:05<00:47, 183.99it/s]
batch_reader:   7%|▋         | 618/9340 [00:05<00:46, 186.13it/s]
batch_reader:   7%|▋         | 637/9340 [00:05<00:46, 185.62it/s]
batch_reader:   7%|▋         | 657/9340 [00:05<00:56, 154.24it/s]
batch_reader:   7%|▋         | 677/9340 [00:05<00:52, 163.98it/s]
batch_reader:   7%|▋         | 697/9340 [00:05<00:50, 171.88it/s]
batch_reader:   8%|▊         | 716/9340 [00:05<00:48, 176.33it/s]
batch_reader:   8%|▊         | 736/9340 [00:06<00:47, 181.41it/s]
batch_reader:   8%|▊         | 755/9340 [00:06<01:33, 91.70it/s] 
batch_reader:   8%|▊         | 770/9340 [00:07<02:24, 59.27it/s]
batch_reader:   8%|▊         | 790/9340 [00:07<01:52, 76.27it/s]
batch_reader:   9%|▊         | 810/9340 [00:07<01:30, 94.23it/s]
batch_reader:   9%|▉         | 830/9340 [00:07<01:16, 111.97it/s]
batch_reader:   9%|▉         | 850/9340 [00:07<01:06, 128.62it/s]
batch_reader:   9%|▉         | 868/9340 [00:07<01:12, 117.57it/s]
batch_reader:  10%|▉         | 888/9340 [00:07<01:02, 134.27it/s]
batch_reader:  10%|▉         | 908/9340 [00:07<00:57, 147.78it/s]
batch_reader:  10%|▉         | 928/9340 [00:07<00:52, 159.26it/s]
batch_reader:  10%|█         | 948/9340 [00:08<00:49, 168.35it/s]
batch_reader:  10%|█         | 968/9340 [00:08<00:47, 174.51it/s]
batch_reader:  11%|█         | 988/9340 [00:08<00:46, 179.26it/s]
batch_reader:  11%|█         | 1006/9340 [00:19<00:46, 179.26it/s]
```

然后就一直在这里卡着，不知道咋办
感谢你

**Comment by rl4940** [comment]
> 你环境里的numpy版本是什么？可否换成1.22.4再试一下：
> 
> ```shell
> pip uninstall numpy
> pip install numpy==1.22.4
> ```

哎woc，有道理，我试试，好像numpy报错了，感恩！
